/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressManager: typeof import('./src/components/AddressManager.vue')['default']
    AdminShell: typeof import('./src/components/admin/AdminShell.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ChatbotWidget: typeof import('./src/components/ChatbotWidget.vue')['default']
    ConfirmDialog: typeof import('./src/components/admin/ConfirmDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainTopBar: typeof import('./src/components/MainTopBar.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableSelect: typeof import('./src/components/SearchableSelect.vue')['default']
    StarRating: typeof import('./src/components/StarRating.vue')['default']
  }
}
