const fs = require('fs');
let content = fs.readFileSync('src/pages/AdminEmployeesView.vue', 'utf8');

const replacements = {
  "Quan ly nhan vien": "Quản lý nhân viên",
  "Danh sach nhan vien": "Danh sách nhân viên",
  "ADMIN xem tat ca nhan vien.": "ADMIN xem tất cả nhân viên.",
  "Nhan vien chi xem duoc danh sach co ban.": "Nhân viên chỉ xem được danh sách cơ bản.",
  "Them nhan vien": "Thêm nhân viên",
  "Lam moi": "Làm mới",
  "Tim theo ten, email, so dien thoai": "Tìm theo tên, email, số điện thoại",
  "Tat ca trang thai": "Tất cả trạng thái",
  "Dang hoat dong": "Đang hoạt động",
  "Tam khoa": "Tạm khóa",
  "Tong nhan vien": "Tổng nhân viên",
  "Tong du lieu": "Tổng dữ liệu",
  "Dang tai danh sach nhan vien...": "Đang tải danh sách nhân viên...",
  "Khong tim thay nhan vien phu hop.": "Không tìm thấy nhân viên phù hợp.",
  ">Nhan vien<": ">Nhân viên<",
  "|| \"Nhan vien\"": "|| \"Nhân viên\"",
  "label=\"nhan vien\"": "label=\"nhân viên\"",
  "Vai tro": "Vai trò",
  ">Lien he<": ">Liên hệ<",
  ">Trang thai<": ">Trạng thái<",
  ">Dia chi<": ">Địa chỉ<",
  ">Thao tac<": ">Thao tác<",
  "Hoat dong": "Hoạt động",
  "Lich su don hang": "Lịch sử đơn hàng",
  "Chinh sua": "Chỉnh sửa",
  "Khoa tai khoan": "Khóa tài khoản",
  "Mo khoa tai khoan": "Mở khóa tài khoản",
  "Sua nguoi dung": "Sửa người dùng",
  "Them nguoi dung moi": "Thêm người dùng mới",
  "Ten dang nhap": "Tên đăng nhập",
  "So dien thoai": "Số điện thoại",
  "Mat khau": "Mật khẩu",
  "Toi thieu 6 ky tu": "Tối thiểu 6 ký tự",
  "Tai khoan dang hoat dong": "Tài khoản đang hoạt động",
  ">Huy<": ">Hủy<",
  "Dang luu...": "Đang lưu...",
  "Cap nhat": "Cập nhật",
  "Them moi": "Thêm mới",
  "Tong don hang": "Tổng đơn hàng",
  "Don thanh cong": "Đơn thành công",
  "Tong tien da chi": "Tổng tiền đã chi",
  "Ma don": "Mã đơn",
  "Ngay dat": "Ngày đặt",
  "Thanh tien": "Thành tiền",
  "Cho xu ly": "Chờ xử lý",
  "Dong goi va xu ly": "Đóng gói và xử lý",
  "Dang giao": "Đang giao",
  "Thanh cong": "Thành công",
  "Yeu cau hoan": "Yêu cầu hoàn",
  "Dang hoan ve": "Đang hoàn về",
  "Da hoan tra": "Đã hoàn trả",
  "Da huy": "Đã hủy",
  "Khong xac dinh": "Không xác định",
  "Khach hang": "Khách hàng",
  "Khach vang lai": "Khách vãng lai",
  "Vui long dien day du Ten dang nhap va Email.": "Vui lòng điền đầy đủ Tên đăng nhập và Email.",
  "Mat khau phai co it nhat 6 ky tu khi tao moi.": "Mật khẩu phải có ít nhất 6 ký tự khi tạo mới.",
  "Xac nhan cap nhat": "Xác nhận cập nhật",
  "Xac nhan them moi": "Xác nhận thêm mới",
  "Ban chac chan muon cap nhat nguoi dung": "Bạn chắc chắn muốn cập nhật người dùng",
  "Ban chac chan muon them nguoi dung": "Bạn chắc chắn muốn thêm người dùng",
  "Xac nhan khoa tai khoan": "Xác nhận khóa tài khoản",
  "Xac nhan mo khoa": "Xác nhận mở khóa",
  "Ban chac chan muon khoa tai khoan": "Bạn chắc chắn muốn khóa tài khoản",
  "Ban chac chan muon mo khoa tai khoan": "Bạn chắc chắn muốn mở khóa tài khoản",
  ">Khoa<": ">Khóa<",
  ">Mo khoa<": ">Mở khóa<",
  "Khong the tai": "Không thể tải",
  "Khong the luu": "Không thể lưu",
  "Khong the cap nhat": "Không thể cập nhật",
  "Vui long kiem tra": "Vui lòng kiểm tra",
  "Da khoa tai khoan": "Đã khóa tài khoản",
  "Da mo khoa tai khoan": "Đã mở khóa tài khoản",
  "Nhap dia chi nhan vien": "Nhập địa chỉ nhân viên",
  "Nhap ten dang nhap": "Nhập tên đăng nhập"
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.split(key).join(value);
}

fs.writeFileSync('src/pages/AdminEmployeesView.vue', content, 'utf8');
