/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
    '/AdminAttributesView': RouteRecordInfo<'/AdminAttributesView', '/AdminAttributesView', Record<never, never>, Record<never, never>>,
    '/AdminBrandsView': RouteRecordInfo<'/AdminBrandsView', '/AdminBrandsView', Record<never, never>, Record<never, never>>,
    '/AdminCustomersView': RouteRecordInfo<'/AdminCustomersView', '/AdminCustomersView', Record<never, never>, Record<never, never>>,
    '/AdminDashboardView': RouteRecordInfo<'/AdminDashboardView', '/AdminDashboardView', Record<never, never>, Record<never, never>>,
    '/AdminHomeView': RouteRecordInfo<'/AdminHomeView', '/AdminHomeView', Record<never, never>, Record<never, never>>,
    '/AdminInventoryView': RouteRecordInfo<'/AdminInventoryView', '/AdminInventoryView', Record<never, never>, Record<never, never>>,
    '/AdminOrdersView': RouteRecordInfo<'/AdminOrdersView', '/AdminOrdersView', Record<never, never>, Record<never, never>>,
    '/AdminPOSView': RouteRecordInfo<'/AdminPOSView', '/AdminPOSView', Record<never, never>, Record<never, never>>,
    '/AdminProductsView': RouteRecordInfo<'/AdminProductsView', '/AdminProductsView', Record<never, never>, Record<never, never>>,
    '/AdminPromotionsView': RouteRecordInfo<'/AdminPromotionsView', '/AdminPromotionsView', Record<never, never>, Record<never, never>>,
    '/AdminSettingsView': RouteRecordInfo<'/AdminSettingsView', '/AdminSettingsView', Record<never, never>, Record<never, never>>,
    '/AdminVouchersView': RouteRecordInfo<'/AdminVouchersView', '/AdminVouchersView', Record<never, never>, Record<never, never>>,
    '/BrandView': RouteRecordInfo<'/BrandView', '/BrandView', Record<never, never>, Record<never, never>>,
    '/CartView': RouteRecordInfo<'/CartView', '/CartView', Record<never, never>, Record<never, never>>,
    '/ChangePasswordView': RouteRecordInfo<'/ChangePasswordView', '/ChangePasswordView', Record<never, never>, Record<never, never>>,
    '/CheckoutView': RouteRecordInfo<'/CheckoutView', '/CheckoutView', Record<never, never>, Record<never, never>>,
    '/CompareView': RouteRecordInfo<'/CompareView', '/CompareView', Record<never, never>, Record<never, never>>,
    '/ForgotPasswordView': RouteRecordInfo<'/ForgotPasswordView', '/ForgotPasswordView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/OrderHistoryView': RouteRecordInfo<'/OrderHistoryView', '/OrderHistoryView', Record<never, never>, Record<never, never>>,
    '/ProductDetailView': RouteRecordInfo<'/ProductDetailView', '/ProductDetailView', Record<never, never>, Record<never, never>>,
    '/ProductView': RouteRecordInfo<'/ProductView', '/ProductView', Record<never, never>, Record<never, never>>,
    '/ProfileEdit': RouteRecordInfo<'/ProfileEdit', '/ProfileEdit', Record<never, never>, Record<never, never>>,
    '/ProfileView': RouteRecordInfo<'/ProfileView', '/ProfileView', Record<never, never>, Record<never, never>>,
    '/RegisterView': RouteRecordInfo<'/RegisterView', '/RegisterView', Record<never, never>, Record<never, never>>,
    '/ReviewFormView': RouteRecordInfo<'/ReviewFormView', '/ReviewFormView', Record<never, never>, Record<never, never>>,
    '/ShopView': RouteRecordInfo<'/ShopView', '/ShopView', Record<never, never>, Record<never, never>>,
    '/SizeGuideView': RouteRecordInfo<'/SizeGuideView', '/SizeGuideView', Record<never, never>, Record<never, never>>,
    '/VnpayReturnView': RouteRecordInfo<'/VnpayReturnView', '/VnpayReturnView', Record<never, never>, Record<never, never>>,
    '/VoucherView': RouteRecordInfo<'/VoucherView', '/VoucherView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/AboutView.vue': {
      routes: '/AboutView'
      views: never
    }
    'src/pages/AdminAttributesView.vue': {
      routes: '/AdminAttributesView'
      views: never
    }
    'src/pages/AdminBrandsView.vue': {
      routes: '/AdminBrandsView'
      views: never
    }
    'src/pages/AdminCustomersView.vue': {
      routes: '/AdminCustomersView'
      views: never
    }
    'src/pages/AdminDashboardView.vue': {
      routes: '/AdminDashboardView'
      views: never
    }
    'src/pages/AdminHomeView.vue': {
      routes: '/AdminHomeView'
      views: never
    }
    'src/pages/AdminInventoryView.vue': {
      routes: '/AdminInventoryView'
      views: never
    }
    'src/pages/AdminOrdersView.vue': {
      routes: '/AdminOrdersView'
      views: never
    }
    'src/pages/AdminPOSView.vue': {
      routes: '/AdminPOSView'
      views: never
    }
    'src/pages/AdminProductsView.vue': {
      routes: '/AdminProductsView'
      views: never
    }
    'src/pages/AdminPromotionsView.vue': {
      routes: '/AdminPromotionsView'
      views: never
    }
    'src/pages/AdminSettingsView.vue': {
      routes: '/AdminSettingsView'
      views: never
    }
    'src/pages/AdminVouchersView.vue': {
      routes: '/AdminVouchersView'
      views: never
    }
    'src/pages/BrandView.vue': {
      routes: '/BrandView'
      views: never
    }
    'src/pages/CartView.vue': {
      routes: '/CartView'
      views: never
    }
    'src/pages/ChangePasswordView.vue': {
      routes: '/ChangePasswordView'
      views: never
    }
    'src/pages/CheckoutView.vue': {
      routes: '/CheckoutView'
      views: never
    }
    'src/pages/CompareView.vue': {
      routes: '/CompareView'
      views: never
    }
    'src/pages/ForgotPasswordView.vue': {
      routes: '/ForgotPasswordView'
      views: never
    }
    'src/pages/HomeView.vue': {
      routes: '/HomeView'
      views: never
    }
    'src/pages/LoginView.vue': {
      routes: '/LoginView'
      views: never
    }
    'src/pages/OrderHistoryView.vue': {
      routes: '/OrderHistoryView'
      views: never
    }
    'src/pages/ProductDetailView.vue': {
      routes: '/ProductDetailView'
      views: never
    }
    'src/pages/ProductView.vue': {
      routes: '/ProductView'
      views: never
    }
    'src/pages/ProfileEdit.vue': {
      routes: '/ProfileEdit'
      views: never
    }
    'src/pages/ProfileView.vue': {
      routes: '/ProfileView'
      views: never
    }
    'src/pages/RegisterView.vue': {
      routes: '/RegisterView'
      views: never
    }
    'src/pages/ReviewFormView.vue': {
      routes: '/ReviewFormView'
      views: never
    }
    'src/pages/ShopView.vue': {
      routes: '/ShopView'
      views: never
    }
    'src/pages/SizeGuideView.vue': {
      routes: '/SizeGuideView'
      views: never
    }
    'src/pages/VnpayReturnView.vue': {
      routes: '/VnpayReturnView'
      views: never
    }
    'src/pages/VoucherView.vue': {
      routes: '/VoucherView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
